enableHardenedMode: false
enableTelemetry: false
nodeLinker: 'node-modules'
npmPublishAccess: 'public'
npmPublishProvenance: true
plugins:
  - path: '.yarn/plugins/plugin-prettier-after-all-installed.cjs'
yarnPath: '.yarn/releases/yarn-4.12.0.cjs'
