jobs:
  upload-dist:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6.0.2'
      - name: 'Rename binary for release'
        run: 'cp dist/index.js facetime-clear-badge'
      - name: 'Upload facetime-clear-badge to draft release'
        uses: 'softprops/action-gh-release@v3.0.0'
        with:
          draft: true
          files: 'facetime-clear-badge'
name: 'Upload dist'
'on':
  push:
    tags:
      - 'v*'
permissions:
  contents: 'write'
