jobs:
  upload-dist:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6.0.2'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v6.4.0'
        with:
          node-version: '24'
      - name: 'Yarn cache'
        uses: 'actions/cache@v5.0.5'
        with:
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}"
          path: '~/.yarn/berry'
          restore-keys: '${{ runner.os }}-yarn'
      - name: 'Install dependencies'
        run: 'yarn'
      - name: 'Build'
        run: 'yarn tsc'
      - name: 'Upload dist/index.js to draft release'
        uses: 'softprops/action-gh-release@v3.0.0'
        with:
          draft: true
          files: 'dist/index.js'
name: 'Upload dist'
'on':
  push:
    tags:
      - 'v*'
permissions:
  contents: 'write'
